config/routes.rb
Rails.application.routes.draw do
  
  resources :goods
  resources :transactions, only: [:new, :create]

  get 'payment/new'

  get 'payment/show'

  get 'payment/_form'

  resources :schools
  resources :children 
  #logins 
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'



  resources :users do 
    post 'change_money' => 'users#change_money'
  end
  # get 'payment', to: 'users#payment', as: 'payment'
  # post "/checkout" => "users#index"

  #Pages
  get 'page/index'
  # root 'page#index'
  root :to => 'sessions#new'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :children
  has_many :purchases
  has_many :goods, through :purchases

  validates :first_name,
            presence: true
  validates :last_name,
            presence: true
  validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }
  def to_s
    "#{first_name} #{last_name}"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show, :edit, :update, :destroy, :change_money]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show

    @user = User.find(params[:id])
    @children = Child.where(:user_id==current_user.id)
  end

  # Adding money to kids
  def change_money 
    @user = User.find(:id==params[:id])
    puts "RUNNING ADD MONEY"
    puts "THE CHILD ID HERE IS #{params[:child_id]}"
    @child = Child.find(params[:child_id])
    puts "THIS IS MONEY FOR #{@child.name}"
    @amount=params[:amount].to_f

    if (params[:add_money] )
      # Redirect to new form, for example.
      if @user.balance >= @amount # add the moneh
        @child.balance+=@amount
        @user.balance-=@amount
        @user.save
        @child.save
      else
        puts "fuck you doubly"
      end 
    else 
      if @child.balance >= @amount
        @child.balance-=@amount
        @user.balance+=@amount
        @user.save
        @child.save
      else 
        puts "fuck you"
      end


    end
      redirect_to user_path(current_user)
  end


  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'User was successfully created.'
    else
      render :new
    end
  end


  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def payment

    @client_token = Braintree::ClientToken.generate 
      # (:customer_id => current_user.id)

    # @client_token = Braintree::ClientToken.generate
    puts @client_token

    params.each do |key,value|
      Rails.logger.warn "Param #{key}: #{value}"
    end
  end  

  def checkout

    nonce = params[:payment_method_nonce]
    post nonce

    result = Braintree::Transaction.sale(
      :amount => "100.00",
      :payment_method_nonce => nonce_from_the_client
    )
    puts "HELLO CHECKING YOU OUT"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/payment.html.erb
<form>  <!-- id="checkout" method="post" action="/checkout" -->
  <div id="dropin"></div>
  <input type="submit" value="Pay $10">
</form>

<script type="text/javascript">
  function setupBT() {
    braintree.setup("<%= @client_token %>", 'dropin', {
      container: 'dropin'
    });
  }
  if (window.addEventListener)
    window.addEventListener("load", setupBT, false);
  else if (window.attachEvent)
    window.attachEvent("onload", setupBT);
  else window.onload = setupBT;
  </script>
</script>

app/views/users/show.html.erb
  <h1> Welcome <%= @user.first_name %> <%= @user.last_name %></h1>


    <div class="col-lg-12">
        <div class="box box-solid box-primary">
        <div class="box-header">
          <h3 class="box-title">Your Balance:</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
          <%= @user.balance %>
        </div><!-- /.box-body -->
      </div>
    </div>



<br> 

<% @children.each do |child| %>
	<div class="child_box col-md-4">
    <div class="box box-solid box-primary">

		<h3><%= child.name %></h3>
		<img src="<%= child.image_url%>">
		<a href="/"><h1><%= School.find(:id==child.school_id).name %></h1></a>
    <h1>Balance: <%= child.balance %></h1> 

    <%= form_tag user_change_money_path(@user) do   %> 
      <input type="float" name="amount" placeholder="Amount">
      <input type="hidden" name="child_id" value=<%=child.id%> />
      <%= submit_tag 'Add Money', name: 'add_money' %>
      <%= submit_tag 'Remove Money' %>
    <% end %> 
    </div>
	</div>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>