config/routes.rb
Rails.application.routes.draw do
  
  resources :goods
  resources :transactions, only: [:new, :create]

  get 'payment/new'

  get 'payment/show'

  get 'payment/_form'

  resources :schools
  resources :children 
  #logins 
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'



  resources :users do 
    post 'change_money' => 'users#change_money'
  end
  # get 'payment', to: 'users#payment', as: 'payment'
  # post "/checkout" => "users#index"

  #Pages
  get 'page/index'
  # root 'page#index'
  root :to => 'sessions#new'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KidsKash</title>
	<%= include_gon %>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<script src="https://js.braintreegateway.com/v2/braintree.js"></script>


</head>
<body>
<div class="wrapper">

<header class="main-header">
  <nav class="navbar navbar-static-top navbar-inverse">
    <div class="container-fluid">
    <div class="navbar-header">
      <a href="/" class="navbar-brand"><b>School</b>Wallet</a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <i class="fa fa-bars"></i>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
		<% if current_user %>
	        <li class="active">
				<%= link_to "My Account", user_path(current_user) %>
	        </li>
	        <li>
				<%= link_to "Log Out", logout_path %>
	        </li>
        <% else %>
	        <li class="active">
				<%= link_to "Sign Up", signup_path %> 
			</li>
			<li>
				<%= link_to "Log In", login_path %>
			</li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

	<% flash.each do |key, value| %>
		<%= content_tag(:div, class: "alert alert-#{key}") do %>
		<p><%= value %></p>
		<% end %>
	<% end %>

	<div class="container">
		<%= yield %>
	</div>

</div>
</body>
</html>